### ISSUE TITLE
Switching from regular job to maker lifestyle

### ISSUE THREAD

**Issue by manish-winux** [chinchang/ask-me-anything#2]
I am following you from long time. You left your job to be a full time maker.
What are your thoughts on this new lifestyle?
How you are going to handle your expenses?
I am just curious.

**Comment by chinchang** [comment]
Hey Manish, thanks for asking.
Both have their own pros and cons. I felt being an independent maker is more suitable for me and so I left my job. Retrospecting now, I am happy I was right. This IS suitable for me.

That said, here are a few things that have changed:

- No one tells me what to do. I like that because I can think and decide more. 👍 👍 
- I can work from anywhere now. 👍 
- My morning routine is not so right nowadays because there is no time table to follow. Kinda bad, but I am trying to get it right. 👎 
- I play a lot more sports now. Good for health. 👍 
- I draw more, play the piano more. Again, good for health and creativity. 👍 
- In short, good things don't have to be left for weekends anymore!! 👍 👍 
- I talk comparatively less. And lot less human interaction. Can't comment yet if that's good or bad. 😐 
- I can't just get any gadget/toy when I feel so because I have to spend wisely. That sucks! 👎 
- I like teaching and sharing what I know. I used to do workshops at my job. Now that hardly happens. Need to fix this. 👎 
- I can help my brother more in his noble initiative! -> https://prakriti.care 👍 
- I have released more than 4 small n big products. So learning has been immense! 👍 

I am living out of my savings right now (for the past 9 months). And I have a few more months runway for me 😄 Hopefully, I start earning decently soon :P 

Hope that helps!

**Comment by yadvr** [comment]
Let's catchup during a weekend @chinchang and make you talk more, we can also explore how you can extend your runway.

**Comment by s0rthak** [comment]
> I talk comparatively less. And lot less human interaction. Can't comment yet if that's good or bad. 😐

I work a full time job and apart from my teammates, that true for me as well. I've started sending meeting invites and zoom video conferencing links to some close friends with moderate success.

**Comment by chinchang** [comment]
@rhtyd Hehe...sure, milte hain!

@batraman Why? Do you remote work too or are there less people at the office to talk to?

**Comment by s0rthak** [comment]
@chinchang In office, we do talk a lot about tech and products but that doesn't fill the culture and philosophy hole. That's where talking to friends outside work help!

**Comment by manishsaraan** [comment]
@chinchang you seems to join the office again. Can you share your experience as indie maker and lessons you have learned from working on your projects. 
PS. This issue was created by me with my office id which I no longer maintain. So you can close it by yourself.

**Comment by chinchang** [comment]
@manishsaraan Sure!
- Being an Indie Maker is a lot of fun! You get to do what you want!
- You can be an Indie Maker along with a fulltime job too. Just that you won't as much time as you might want to dedicate.
- Release quickly whatever you have. Take feedback and iterate. Don't keep implementing features for more than 2 weeks.
- Don't put dependencies on other things. Eg. Don't think that once I have 2-3 article ideas then I'll start a blog. No! Start a blog, put out at least one article out in public...try to be consistent. Each article will give you motivation n boost.
